apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260627-210212-d9ih9jv8b5cf-service
spec:
  selector:
    app: enterprise-system-20260627-210212-d9ih9jv8b5cf
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
